# name: CI

# on:
#   pull_request:
#     branches: [ develop ]  # PR ëŒ€ìƒ ë¸Œëžœì¹˜

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: ðŸ“¥ Checkout repository
#         uses: actions/checkout@v3

#       - name: â˜• Set up JDK 17
#         uses: actions/setup-java@v3
#         with:
#           java-version: '17'
#           distribution: 'temurin'

#       - name: ðŸ›  Create application-test.yml from secret
#         run: |
#           mkdir -p src/main/resources
#           echo "${{ secrets.APPLICATION_TEST_YML }}" > src/main/resources/application-test.yml

#       - name: ðŸ”¨ Build with Gradle
#         run: ./gradlew clean build

#       - name: âœ… Run Tests
#         run: ./gradlew test -Dspring.profiles.active=test


